### ISSUE TITLE
More playback rates

### ISSUE THREAD

**Issue by hijuuijj** [bikegriffith/clappr-playback-rate-plugin#15]
Could you add playback rates? (like VLC)

0.02x
0.03x
0.06x
0.12x
0.25x
0.33x
0.50x
0.67x
1.00x (Normal)
1.50x
2.00x
3.00x
4.00x
8.00x
16.00x
32.00x
64.00x

**Comment by bikegriffith** [comment]
As documented in the readme, you can add additinoal playback rates as you wish. See the example on the homepage:

```
var player = new Clappr.Player({
  source: "http://your.video/here.m3u8",
  plugins: {
    'core': [Clappr.MediaControl, PlaybackRatePlugin]
  },
  playbackRateConfig: {
    defaultValue: '1.0',
    options: [
        {value: '0.5', label: '0.5x'},
        {value: '1.0', label: '1x'},
        {value: '2.0', label: '2x'},
    ]
  },
});
```

**Comment by hijuuijj** [comment]
I meant, add those by default. I think the default ones are few.

  playbackRateConfig: {
    defaultValue: 'Normal',
    options: [
        {value: '0.10', label: '0.10x'},
        {value: '0.25', label: '0.25x'},
        {value: '0.50', label: '0.50x'},
        {value: '0.75', label: '0.75x'},
        {value: '1.00', label: 'Normal'},
        {value: '1.25', label: '1.25x'},
        {value: '1.50', label: '1.50x'},
        {value: '1.75', label: '1.75x'},
        {value: '2.00', label: '2.00x'},
    ]
  },

**Comment by bikegriffith** [comment]
Ahh gotcha.  I think for right now I'm going to leave the default at the limited subset, but I appreciate the feedback.

**Comment by hijuuijj** [comment]
And in my opinion, 1.00x looks better than "Normal"

https://i.ibb.co/8N6TrrZ/capture.png

Thank you for your plugin.
