### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by katsar0v** [bikegriffith/clappr-playback-rate-plugin#18]
Hello, 
I tried to install the plugin, but it does not seem to work with the latest clappr version. There have been no commits lately, so I wanted to ask if this plugin is maintained or accepting PR? Thanks

**Comment by kslimani** [comment]
Hello @katsar0v , this issue should be fixed soon by #17.

**Comment by katsar0v** [comment]
Very nice!

**Comment by bikegriffith** [comment]
This is now released as v0.6.0! Thank you @kslimani
