### ISSUE TITLE
Chrome Android

### ISSUE THREAD

**Issue by andresjuarez** [bikegriffith/clappr-playback-rate-plugin#4]
Hello, I'm trying to run this plugin and works ok on Desktop web browsers, but currently I have a problem trying on Android. I'm trying on several devices using Chrome (Version 51.0.2704.81 and olders), the menu is showing perfectly but when I try change the plaback rate don't do anything.

By the way I recommend publish a CDN to be easier the test on cdn.clappr.io

Cheers

**Comment by bikegriffith** [comment]
Unfortunately [playbackRate isn't implemented on Chrome for Android](https://bugs.chromium.org/p/chromium/issues/detail?id=263654).  We could blacklist the display of the menu, but I hate doing that because we'd have to pull it out if/when they eventually implement support.
