### ISSUE TITLE
Reference Error with latest clappr build

### ISSUE THREAD

**Issue by nburt** [bikegriffith/clappr-playback-rate-plugin#5]
I'm currently in the process of integrating Clappr and came across this plugin which we'd like to add.

I've installed version 0.2.0 with version 0.2.64 of Clappr with NPM and integrated the plugin into a React app following the docs.

The error I see on page load is: `ReferenceError: external undefined plugin on core array`

I searched around and saw an issue for another Clappr plugin from about a year back (https://github.com/clappr/clappr-level-selector-plugin/issues/7). Could a recent Clappr version have broken the plugin?

Please let me know if there's any other info I can provide. Thanks!

Nate

**Comment by bikegriffith** [comment]
@nburt Thanks for the report!  Please give this recent change a try and if you're still having issues reopen this issue and let me know.

**Comment by nburt** [comment]
@bikegriffith Thanks for taking a look so quickly.

I still seem to be getting the same error message on v0.3.0. I put a breakpoint in `validateExternalPluginsType` within Clappr and I'm getting an empty object:

![image](https://cloud.githubusercontent.com/assets/5788989/21608951/aeb310f0-d18d-11e6-8882-5638aa3d33e0.png)

Maybe I'm importing incorrectly? I installed using npm and imported just as in the docs:

```
import Clappr from 'clappr';
import PlaybackRatePlugin from 'clappr-playback-rate-plugin';
```

We ended up having to rebuild the media controls from scratch for other reasons so I'm not sure we'll be using the playback plugin in the project anymore but I'll see if I can create a small repo to reproduce this week if it's working locally for you.

**Comment by nburt** [comment]
@bikegriffith I was just able to get this to work.

Switching from `import PlaybackRatePlugin from 'clappr-playback-rate-plugin';` to `import PlaybackRatePlugin from 'clappr-playback-rate-plugin/dist/clappr-playback-rate-plugin';` did the trick
