### ISSUE TITLE
How listen on change rate?

### ISSUE THREAD

**Issue by argentinaluiz** [bikegriffith/clappr-playback-rate-plugin#6]
Hi,
I have the instance Clappr player and how listen on change rate event?

**Comment by bikegriffith** [comment]
@argentinaluiz There's no method right now to do it, but if you want to submit a PR, you could potentially check for a passed-in callback function around https://github.com/bikegriffith/clappr-playback-rate-plugin/blob/master/src/main.js#L95, then fire the callback, passing the new rate value in there.

**Comment by argentinaluiz** [comment]
@bikegriffith Thanks! I will make this. ;)
