### ISSUE TITLE
Wrong selector for changing rate

### ISSUE THREAD

**Issue by marcosox** [bikegriffith/clappr-playback-rate-plugin#9]
Hello, I found a small bug your plugin.
When using an `audioOnly` media element, the plugin doesn't change the playback rate. This is due to [this jQuery selector in line 122](https://github.com/bikegriffith/clappr-playback-rate-plugin/blob/master/src/main.js#L122) that looks only for `video` elements even when `audioOnly` is set to true. A simple check for this flag that uses the right selector should be enough, since I can confirm replacing `video` with `audio` returns the correct element.

**Comment by bikegriffith** [comment]
Yes, you are correct. Will fix and publish a new version.
